# Generated by Django 4.1 on 2022-11-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("email", models.EmailField(max_length=100, null=True)),
                ("message", models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=100, null=True)),
                ("password", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Signup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstname", models.CharField(max_length=30, null=True)),
                ("lastname", models.CharField(max_length=30, null=True)),
                ("email", models.EmailField(max_length=100, null=True)),
                ("password", models.TextField(max_length=30, null=True)),
                ("presentAdd", models.TextField(max_length=150, null=True)),
                ("parmanentAdd", models.TextField(max_length=150, null=True)),
                ("city", models.TextField(max_length=50, null=True)),
            ],
        ),
    ]
