# Generated by Django 4.1 on 2022-11-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("new", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="signup",
            name="code",
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
