# Generated by Django 4.1 on 2022-12-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("new", "0002_signup_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
