# Generated by Django 4.1 on 2022-12-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("new", "0002_signup_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                # ("firstname", models.CharField(max_length=30, null=True)),
                ("FlightNo", models.TextChoices('FlightNo', 'BA3882 BA3871 BA3333')),
                ("Type", models.TextChoices('Type', 'A B C')),
                ("Origin", models.TextChoices('Origin', 'Dhaka Chattogram Khulna')),
                ("Destination", models.TextChoices('Destination', 'Dhaka Chattogram Khulna')),
                ("DepartureTime", models.TextChoices('DepartureTime', '7am 9am 11am 1pm 3pm 5pm 7pm')),
                ("ArrivalTime", models.TextChoices('ArrivalTime', '7am 9am 11am 1pm 3pm 5pm 7pm')),
            ],
        ),
    ]
